server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/flexfolio}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: 0afe0fbfbe59e9d698997152b429ecbcf72da01b3ddc3fcf38bb13936899815a
  expiration: 86400000  # 24 hours in milliseconds
